apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    namespace = "com.android.app.animation"
    testNamespace = "com.android.app.animation.tests"
    defaultConfig {
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    sourceSets {
        main {
            java.srcDirs = ['src']
            res.srcDirs = ['res']
            manifest.srcFile 'AndroidManifest.xml'
        }
        androidTest {
            java.srcDirs = ["tests/src"]
            manifest.srcFile 'tests/AndroidManifest.xml'
        }
    }
    lintOptions {
        abortOnError false
    }
    tasks.lint.enabled = false
    tasks.withType(JavaCompile) {
        options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
    }
}

addFrameworkJar('framework-16.jar')

dependencies {
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:2.2.10'
    implementation 'androidx.core:core-animation:1.0.0'
    implementation 'androidx.core:core-ktx:1.17.0'
}
